# Generated by Django 4.0.1 on 2022-02-15 16:51

import Reg_login_logout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_login_logout', '0006_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='price',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Reg_login_logout.models.uploaded_file_path),
        ),
    ]
