# Generated by Django 4.0.1 on 2022-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_login_logout', '0007_uploadfile_price_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
