# Generated by Django 4.0.1 on 2022-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reg_login_logout', '0008_userprofile_stripe_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='stripe_product_info',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
